### PR TITLE
Shallow populate fix

### PR DESCRIPTION
**Pull request by aliciahogue**
### Summary

(If you have not already please refer to the contributing guideline as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#pull-requests))

reference issue - https://github.com/marshallswain/feathers-graph-populate/issues/19

If so, please mention them to keep the conversations linked together.

### Other Information

If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.

Your PR will be reviewed by a core team member and they will work with you to get your changes merged in a timely manner. If merged your PR will automatically be added to the changelog in the next release.

If your changes involve documentation updates please mention that and link the appropriate PR in [feathers-docs](https://github.com/feathersjs/feathers-docs).

Thanks for contributing to Feathers! :heart:

### CODE REVIEW

**Comment by marshallswain** [comment]
I just realized that we should flip the logic and instead of checking for the get method, we should check for the find method, since it has the only unique response compared to the other requests.

**Comment by aliciahogue** [comment]
Done!

**Comment by aliciahogue** [comment]
Do you guys need anything else for this to be merged in?

**Comment by marshallswain** [comment]
@aliciahogue That took way too long.  So sorry that I've been so busy!

**Comment by marshallswain** [comment]
Released in `feathers-shallow-populate@2.2.0`!  Thank you!

**Pull request merged**
